spring:
  application:
    name: mvc-app

  # JPA Configuration for Spring MVC
  datasource:
    url: jdbc:postgresql://localhost:5432/benchmark
    username: benchmark_user
    password: benchmark_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Logging configuration
logging:
  level:
    me.bossm0n5t3r: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
logging:
  level:
    me.bossm0n5t3r: DEBUG
    org.springframework.web: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
logging:
  level:
    root: WARN
    me.bossm0n5t3r: INFO

---
# Benchmark profile
spring:
  config:
    activate:
      on-profile: benchmark
  jpa:
    show-sql: false
logging:
  level:
    root: WARN
    me.bossm0n5t3r: ERROR