spring:
  application:
    name: webflux-app

  # R2DBC Configuration for Spring WebFlux
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/benchmark
    username: benchmark_user
    password: benchmark_pass

server:
  port: 8081

# Logging configuration
logging:
  level:
    root: WARN
    me.bossm0n5t3r: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
